name: 'demo_dbt'

version: '1.0.0'


profile: 'athena'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:       
  - "target"
  - "dbt_packages"



models:
  demo_dbt:
    example:
      +materialized: view
